# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://kanye0405.github.io
date_format: "ordinal"
title: Kanye的个人博客
subtitle: "会一点代码的咸鱼"
description: "李振羽的个人博客"
keywords: Kanye, 节命, 李振羽, Java, JavaScript
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Zhenyu Li
organization: 旅宝
organization_url: https://www.lvbaoyou.com
location: Hangzhou, China
email: lizhenyu093@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: kanye0405/kanye0405.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: kanye0405
zhihu_username: 李振羽

# ---------------- #
#      Comments    #
# ---------------- #
duoshuo_username: kanye0405

# ---------------- #
#    Analytics     #
# ---------------- #

google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_java_keywords: [Java, Spring, Dubbo,rabbitMQ, Elastic Search]
skill_front_end_keywords: [JavaScript, Nodejs, Css, Html, React, Vue]
skill_datebase_keywords: [Mysql, Redis ,Mongodb]